Repository joshuaellis/react-tensorflow, pull requests merged in 2020-11, with the labels that each got.

#9 bug: RTF-6
  src/helpers/attachWebcam.ts
  src/hooks/useWebcam.ts
Labels: bug

#13 Bugfix/rtf-7
  __mocks__/@tensorflow/tfjs/index.js
  src/helpers/image.ts
  src/hooks/__test__/useWebcam.test.tsx
  src/hooks/useWebcam.ts
Labels: bug

#16 Feature/rtf-14
  __mocks__/@tensorflow/tfjs/index.js
  __test__/codeConform.test.ts
  src/hooks/__test__/useModel.test.tsx
  src/hooks/__test__/useWebcam.test.tsx
  src/hooks/useModel.ts
  src/hooks/usePrediction.ts
  src/types/index.ts
Labels: enhancement

#17 Spike/rtf 15
  __mocks__/@tensorflow/tfjs/index.ts
  src/hooks/__test__/usePrediction.test.ts
  src/hooks/usePrediction.ts
  src/types/index.ts
Labels: change

#19 typo fix in prediction page example
  example/src/containers/PagePrediction/index.tsx
Labels: docs

#21 Improvement/rtf-20
  README.md
  src/hooks/__test__/usePrediction.test.ts
  src/hooks/__test__/useWebcam.test.tsx
  src/hooks/usePrediction.ts
  src/types/index.ts
Labels: improvement
